### ISSUE TITLE
怎么添加视频

### ISSUE THREAD

**Issue by SineLabo** [hustlzp/XEditor#16]
在演示网站上，想要插入视频。
发现在富文本编辑模式下，插入以下代码：
```html
<iframe height=498 width=510 src="http://player.youku.com/embed/XMjI2MjU3MDMy" frameborder=0 allowfullscreen></iframe>
```
切换到md模式再切换到富文本，视频出现了，
但是再切换后，代码就没了，这个是什么问题？

想问：正常插入视频的方式是怎样的？
----

**Comment by hustlzp** [comment]
现在可以了，支持youku的iframe和embed标签。

之前不行是因为富文本编辑器过滤了iframe和embed标签。

**Comment by SineLabo** [comment]
非常感谢
